### ISSUE TITLE
Dell R630 IPMI integration stuck on "Gathering MC info"

### ISSUE THREAD

**Issue by isnuryusuf** [digitalrebar/provision#1126]
Hi Support team

i try to using IPMI-configure on Dell R630 to achieve configuring IPMI user and password
this is the log from JOB LOG FOR IPMI-CONFIGURE
```
Log for Job: f44899d7-908b-41fd-8cc7-89e8a0536a12
Starting task yhs-workflow-discovery-ipmi-setup:yhs-ipmi-configure:yhs-ipmi-configure on d14-18-77-31-4b-f9.baremetal.yusuf.net
2019-03-19 13:31:28.537401822 +0000 GMT m=+904.112723810: Writing ipmi-quirks.yaml.tmpl to /tmp/runner-644317489/yhs-ipmi-configure-851973594/ipmi-quirks.yaml
Action ipmi-quirks.yaml.tmpl finished
Starting command ./yhs-ipmi-configure-ipmi-install.sh.tmpl



Command running
ipmitool already installed.
Command exited with status 0
Action ipmi-install.sh.tmpl finished
Starting command ./yhs-ipmi-configure-ipmi-configure.sh.tmpl


Command running
Loading IPMI modules
Gathering MC info
```

snippet ipmi-quirks.yaml.tmpl related to Dell HW
```
dell-rseries:
  quirklist:
  - ipmi-nodelay
  - ipmi-dell-dedicated-nic
  match:
    bmcinfo:
      device_id:
        __sm_leaf: true
        op: ==
        match: "32"
      mfgr_id:
        __sm_leaf: true
        op: ==
        match: "674"
        score: 5
      product_id:
        __sm_leaf: true
        op: ==
        match: 256 (0x0100)
        score: 3
```

ipmitool -vI lanplus -H 10.110.0.117 -U root -P password mc info
```
Device ID                 : 32
Device Revision           : 1
Firmware Revision         : 2.61
IPMI Version              : 2.0
Manufacturer ID           : 674
Manufacturer Name         : DELL Inc
Product ID                : 256 (0x0100)
Product Name              : Unknown (0x100)
Device Available          : yes
Provides Device SDRs      : yes
Additional Device Support :
    Sensor Device
    SDR Repository Device
    SEL Device
    FRU Inventory Device
    IPMB Event Receiver
    Bridge
    Chassis Device
Aux Firmware Rev Info     : 
    0x00
    0x08
    0x3c
    0x3c

```

after waiting for 10 minutes,  is still stuck on Gathering MC info

can you share the sledgehammer default username and password?
so i can check manually running ipmitool on the sledgehammer OS running on DELL R630

thnks  in advanced
