### ISSUE TITLE
ExtraClaims in uploaded bundle are not preserved

### ISSUE THREAD

**Issue by avanier** [digitalrebar/provision#492]
I'm working on a bundle where a task needs an `ExtraClaims`.

When uploading the bundle, no errors are declared, but listing the tasks reveals the task without its `ExtraClaims` statement.

I'm running `v4.5.4`.

I think this might be specific to updating tasks, or something related to bundles, as I do not have a problem creating a new task with claims, and editing the claims thereafter.

<details>
  <summary>Example Objects</summary>

  Given this task

  ```yaml
  ---
  Description: This task should have some ExtraClaims
  ExtraClaims:
    - scope: "*"
      action: "*"
      specific: "*"
  Name: new-task-with-claims
  Meta:
    color: black
    icon: tasks
    title: hepderp
    feature-flags: sane-exit-codes
  ```

   A claimless task is returned:

   ```shell
   drpcli tasks show new-task-with-claims
   ```

  ```json
    {
    "Available": true,
    "Bundle": "ax-drp-config",
    "Description": "This task should have some ExtraClaims",
    "Documentation": "",
    "Endpoint": "",
    "Errors": [],
    "Meta": {
      "color": "black",
      "feature-flags": "sane-exit-codes",
      "icon": "tasks",
      "title": "hepderp"
    },
    "Name": "new-task-with-claims",
    "OptionalParams": [],
    "Prerequisites": [],
    "ReadOnly": true,
    "RequiredParams": [],
    "Templates": [],
    "Validated": true
  }
  ```
</details>
